"""Render PREPROCESS_LOG.md from the JSON written by the pipeline (no hand-typed numbers)."""

from __future__ import annotations

import json
from pathlib import Path

from . import schema
from .provenance import ROOT


def _load(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def render_preprocess_log(cfg: dict, ds_list: list[str], smoke: bool = False) -> str:
    proc = Path(cfg["processed_dir"])
    proc = proc if proc.is_absolute() else ROOT / proc
    L = ["# Preprocessing log", ""]
    if smoke:
        L += ["> **SMOKE RUN on synthetic NF-v3-schema data. Not a result.**", ""]
    L += ["Generated by `scripts/prepare.py` from the pipeline JSON. Do not edit by hand.", "",
          "## Fixed drop rules (spec §4)", "", "| Column | Reason |", "|---|---|"]
    for c, r in schema.drop_map(cfg["keep_ttl"]).items():
        if c in schema.INTERNAL:
            continue
        L.append(f"| `{c}` | {r} |")
    L += ["", f"Window T={cfg['window']['T']}, stride={cfg['window']['stride']}, "
              f"group block={cfg['window']['block_ms'] / 3.6e6:g} h; balance {cfg['balance']}", ""]
    common = _load(proc / "common_features.json")
    if common:
        L += [f"## Common feature list ({len(common['features'])})", "",
              ", ".join(f"`{c}`" for c in common["features"]), ""]
        if common.get("partial"):
            L += ["> Partial: built from " + ", ".join(common["datasets"]) + " only.", ""]
    for ds in ds_list:
        info = _load(proc / ds / "index_meta.json")
        if not info:
            continue
        L += [f"## {ds} — {info['name']}", "",
              f"- flows: {info['flows']}; windows: {info['windowing']['windows']}; "
              f"duplicates removed: {info['dedupe']['duplicates_removed']} "
              f"(label conflicts among duplicates: {info['dedupe']['duplicate_label_conflicts']})",
              f"- flows in no window (group tails / short groups): {info['windowing']['flows_not_in_any_window']}; "
              f"majority ties: {info['windowing']['majority_ties']}",
              f"- benign windows after dedupe: {info['benign_windows_after_dedupe']}; LOACO allowed: {info['loaco_allowed']}",
              ""]
        for scheme, s in info["schemes"].items():
            L += [f"### {ds} / {scheme}", "",
                  f"- windows per split: {s['split']['windows']}",
                  f"- cleaner fitted on {s['cleaner_fit_rows']} train-group flows",
                  f"- test classes absent from train: {s['composition']['test_classes_absent_from_train'] or 'none'}",
                  "", "| Dropped by cleaner | Reason |", "|---|---|"]
            for c, r in s["cleaner_dropped"].items():
                if c not in schema.drop_map(cfg["keep_ttl"]):
                    L.append(f"| `{c}` | {r} |")
            L += ["", "| Set | benign | attack | available benign | available attack |", "|---|---|---|---|---|"]
            for k in ("train", "val", "test"):
                v = s["sets"][k]
                L.append(f"| {k} | {v['benign']} | {v['attack']} | {v['available_benign']} | {v['available_attack']} |")
            L += ["", "| LOACO class | train windows | eligible | feasible | note |", "|---|---|---|---|---|"]
            if "skipped" in s["loaco"]:
                L.append(f"| — | — | — | — | {s['loaco']['skipped']} |")
            else:
                for c, v in s["loaco"].items():
                    L.append(f"| {c} | {v['train_windows_majority']} | {v['eligible']} | "
                             f"{v.get('feasible', '—')} | {v.get('reason', '')} |")
            n_ok = sum(1 for v in s["verification"] if v["ok"])
            L += ["", f"Verification: {n_ok}/{len(s['verification'])} checks passed (fail-closed).", ""]
    return "\n".join(L) + "\n"
