#!/usr/bin/env python
"""Generate every LaTeX table of the NOMS 2027 paper from results JSON only.

Inputs: results/final/summary.json (final run, one code commit), the recorded gate JSON of
P1/P1b/P1c/P1d, data/processed/*/index_meta.json (dataset table).
Output: paper/noms2027/tables/*.tex (included by main.tex). No number is typed by hand.

  python paper/noms2027/make_tables.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "tables"
sys.path.insert(0, str(ROOT / "scripts"))
from final_run import BEN, CLAD_, CONF, REPR, TRANSFER_TARGETS, XGB  # noqa: E402

S = json.loads((ROOT / "results/final/summary.json").read_text())
CS, I, T, F = S["class_evals"], S["indist"], S["transfer"], S["feasibility"]
FAMS = ["confidence", "representation", "benign-only", "CLAD", "XGBoost"]
NOV = ["confidence", "representation", "benign-only", "CLAD"]
EV = ["loaco_D1fam", "loaco_D2", "loaco_D3", "loaco_D5pb", "nn_D1", "nn_D3", "nn_D5"]
EVN = {"loaco_D1fam": "LOACO D1 (families)", "loaco_D2": "LOACO D2", "loaco_D3": "LOACO D3",
       "loaco_D5pb": "Purged LOACO D5", "nn_D1": "Natural nov.\\ D1", "nn_D3": "Natural nov.\\ D3",
       "nn_D5": "Natural nov.\\ D5"}
DETN = {"MSP": "MSP", "Energy": "Energy", "P_attack": "P(attack)$^\\dagger$", "AHSD_stress": "Stress",
        "Mahalanobis": "Mahalanobis", "kNN": "kNN", "IF": "IF", "OCSVM": "OCSVM", "PCA": "PCA", "AE": "AE",
        "Wilkie_CLAD": "CLAD", "XGBoost": "XGBoost"}
DETS = CONF + REPR + BEN + [CLAD_, XGB]


def esc(s):
    return str(s).replace("_", "\\_").replace("&", "\\&").replace("%", "\\%")


def f3(x):
    return f"{x:.3f}"


def ci(v, sign=False):
    f = "+.3f" if sign else ".3f"
    return f"{v['mean']:{f}} [{v['ci95'][0]:{f}}, {v['ci95'][1]:{f}}]"


def write(name, body):
    OUT.mkdir(exist_ok=True)
    (OUT / f"{name}.tex").write_text("% generated by paper/noms2027/make_tables.py from results JSON; do not edit\n" + body)


def det_mean(e, d, key="cells"):
    st = CS[e]
    return float(np.mean([st[key][d][c]["mean"] for c in st["classes"]]))


# ---------------------------------------------------------------- datasets (Sec. IV)
def t_datasets():
    rows = []
    names = {"D1": "NF-CSE-CIC-IDS2018-v3", "D2": "NF-UNSW-NB15-v3", "D3": "NF-ToN-IoT-v3",
             "D4": "NF-BoT-IoT-v3", "D5": "LYCOS-IDS2017"}
    role = {"D1": "LOACO, NN, transfer", "D2": "LOACO, transfer", "D3": "LOACO, NN, transfer",
            "D4": "transfer target", "D5": "NN, purged LOACO"}
    for ds in ("D1", "D2", "D3", "D4", "D5"):
        m = json.loads((ROOT / f"data/processed/{ds}/index_meta.json").read_text())
        rows.append(f"{ds} & {names[ds]} & {m['flows']:,} & {m['dedupe']['windows_after']:,} & {len(m['classes']) - 1} & {role[ds]} \\\\")
    write("datasets", "\\begin{table}[t]\n\\centering\\scriptsize\\setlength{\\tabcolsep}{1.8pt}\n"
          "\\caption{Datasets. Windows are counted after global deduplication.}\\label{tab:datasets}\n"
          "\\begin{tabular}{llrrrl}\n\\toprule\nID & Dataset & Flows & Windows & Att.\\ cl. & Role \\\\\n\\midrule\n"
          + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


# ---------------------------------------------------------------- C1 feasibility
def t_feasibility():
    D = F["datasets"]
    rows = []
    for ds in ("D1", "D2", "D3", "D5"):
        r = D[ds]
        nn = F["natural_novelty"].get(f"nn_{ds}", {}).get("classes", [])
        gr = f"{r['loaco_family_grouped_random']} (fam.)" if "loaco_family_grouped_random" in r else str(r["loaco_grouped_random"])
        rows.append(f"{ds} & {gr} & {r['loaco_temporal_gap']} & {len(nn)} \\\\")
    pb = F["d5_purged_block"]
    write("feasibility", "\\begin{table}[t]\n\\centering\\scriptsize\n"
          "\\caption{Protocol feasibility: feasible LOACO folds per split and natural-novelty (NN) classes.}"
          "\\label{tab:feasibility}\n\\begin{tabular}{lccc}\n\\toprule\n"
          "Dataset & LOACO, grouped & LOACO, temporal & NN classes \\\\\n\\midrule\n" + "\n".join(rows)
          + f"\n\\midrule\nD5 purged block & \\multicolumn{{2}}{{c}}{{{len(pb['feasible'])} ({esc(', '.join(pb['feasible']))})}} & -- \\\\\n"
          "\\bottomrule\n\\end{tabular}\n\\end{table}\n")


# ---------------------------------------------------------------- C2 families
def t_families():
    rows = []
    for e in EV:
        st = CS[e]
        lead = max(NOV, key=lambda f: st["families"][f]["mean"])
        cells = []
        for f in FAMS:
            v = st["families"][f]["mean"]
            s = f3(v)
            if f == lead:
                s = f"\\textbf{{{s}}}"
            if f == "XGBoost" and v >= st["families"][lead]["mean"]:
                s = f"\\underline{{{s}}}"
            cells.append(s)
        rows.append(f"{EVN[e]} & {st['n_classes']} & " + " & ".join(cells) + " \\\\")
    write("families", "\\begin{table}[t]\n\\centering\\scriptsize\\setlength{\\tabcolsep}{2.6pt}\n"
          "\\caption{Family mean AUC (5 seeds). Bold: leading novelty family. Underlined: XGBoost $\\geq$ leading "
          "novelty family. Conf.\\ = MSP, Energy, P(attack); Repr.\\ = stress, Mahalanobis, kNN; Benign = IF, OCSVM, "
          "PCA, AE.}\\label{tab:families}\n\\begin{tabular}{lcccccc}\n\\toprule\n"
          "Evaluation & Cl. & Conf. & Repr. & Benign & CLAD & XGB \\\\\n\\midrule\n" + "\n".join(rows)
          + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


# ---------------------------------------------------------------- C3 seed std
def t_seedstd():
    lo = ["loaco_D1fam", "loaco_D2", "loaco_D3"]
    nn = ["nn_D1", "nn_D3", "nn_D5"]

    def pooled(evals, d):
        return float(np.mean([CS[e]["cells"][d][c]["std"] for e in evals for c in CS[e]["classes"]]))
    rows = []
    for d in CONF + REPR + [CLAD_, "IF", "AE"]:
        a, b = pooled(lo, d), pooled(nn, d)
        rows.append(f"{DETN[d]} & {a:.3f} & {b:.3f} & {b / a:.1f}$\\times$ \\\\")
    write("seedstd", "\\begin{table}[t]\n\\centering\\scriptsize\n"
          "\\caption{Mean seed std of AUC over classes: LOACO (D1 families, D2, D3) vs natural novelty (D1, D3, D5). "
          "OCSVM, PCA and XGBoost are deterministic (std 0) and omitted.}\\label{tab:seedstd}\n"
          "\\begin{tabular}{lccc}\n\\toprule\nDetector & LOACO & Natural nov. & Ratio \\\\\n\\midrule\n"
          + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


# ---------------------------------------------------------------- C4 confidence
def t_confidence():
    rows = []
    for e in ["loaco_D2", "loaco_D3", "nn_D3", "nn_D5"]:
        st = CS[e]
        rows.append(f"{EVN[e]} & {f3(det_mean(e, 'MSP'))} & {f3(det_mean(e, 'Energy'))} & {f3(det_mean(e, 'P_attack'))} & "
                    f"{f3(st['families']['representation']['mean'])} \\\\")
    write("confidence", "\\begin{table}[t]\n\\centering\\scriptsize\n"
          "\\caption{Confidence-magnitude scores vs the attack probability and representation distance (mean AUC over "
          "classes).}\\label{tab:confidence}\n\\begin{tabular}{lcccc}\n\\toprule\n"
          "Evaluation & MSP & Energy & P(attack)$^\\dagger$ & Repr. \\\\\n\\midrule\n" + "\n".join(rows)
          + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


# ---------------------------------------------------------------- C5 temporal + transfer
def t_temporal():
    rows = []
    for ds in ("D1", "D2", "D3", "D5"):
        g, t = I[f"indist_{ds}_grouped_random"]["best"], I[f"indist_{ds}_temporal_gap"]["best"]
        pg, pt = g["P_attack"]["test"]["auc"], t["P_attack"]["test"]["auc"]
        xg, xt = g[XGB]["test"]["auc"], t[XGB]["test"]["auc"]
        rows.append(f"{ds} & {pg['mean']:.3f} & {pt['mean']:.3f} ({pt['std']:.3f}) & {xg['mean']:.3f} & {xt['mean']:.3f} \\\\")
    write("temporal", "\\begin{table}[t]\n\\centering\\scriptsize\\setlength{\\tabcolsep}{3pt}\n"
          "\\caption{In-distribution AUC under grouped-random vs temporal splits (seed std in brackets). XGBoost is "
          "deterministic. One neural backbone.}\\label{tab:temporal}\n\\begin{tabular}{lcccc}\n\\toprule\n"
          " & \\multicolumn{2}{c}{AHSD P(attack)$^\\dagger$} & \\multicolumn{2}{c}{XGBoost} \\\\\n"
          "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\nDataset & grouped & temporal & grouped & temporal \\\\\n\\midrule\n"
          + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


def t_transfer():
    tg = ["D1", "D2", "D3", "D4"]
    rows = []
    for d in DETS:
        for s in TRANSFER_TARGETS:
            rows.append(f"{DETN[d] if s == 'D1' else ''} & {s} & " + " & ".join(
                (f"\\textit{{{T[d][s][t]['mean']:.3f}}}" if t == s else f"{T[d][s][t]['mean']:.3f}") if t in T[d][s] else "--"
                for t in tg) + " \\\\")
        rows.append("\\addlinespace[1pt]")
    write("transfer", "\\begin{table}[t]\n\\centering\\scriptsize\\setlength{\\tabcolsep}{3pt}\n"
          "\\caption{Zero-shot transfer AUC (rows: source; columns: target; italic: in-domain test).}\\label{tab:transfer}\n"
          "\\begin{tabular}{llcccc}\n\\toprule\nDetector & Src & D1 & D2 & D3 & D4 \\\\\n\\midrule\n"
          + "\n".join(rows[:-1]) + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


# ---------------------------------------------------------------- appendix: per-class AUC
def t_perclass():
    blocks = []
    for e in EV:
        st = CS[e]
        cls = st["classes"]
        head = " & ".join(esc(c.replace("Infilteration", "Infiltration")) for c in cls)
        rows = []
        for d in DETS:
            rows.append(f"{DETN[d]} & " + " & ".join(f"{st['cells'][d][c]['mean']:.2f}\\,({st['cells'][d][c]['std']:.2f})"
                                                     for c in cls) + " \\\\")
        blocks.append(f"\\multicolumn{{{len(cls) + 1}}}{{l}}{{\\textbf{{{EVN[e]}}}}} \\\\\n"
                      f"Detector & {head} \\\\\n\\midrule\n" + "\n".join(rows))
    body = []
    for i, b in enumerate(blocks):
        ncol = len(CS[EV[i]]["classes"]) + 1
        body.append(f"\\begin{{tabular}}{{l{'c' * (ncol - 1)}}}\n\\toprule\n{b}\n\\bottomrule\n\\end{{tabular}}\\par\\medskip\n")
    head = ("\\begin{table*}[!t]\n\\centering\\scriptsize\\setlength{\\tabcolsep}{2.4pt}\n\\caption{Per-class AUC, mean over 5 "
            "seeds (seed std in brackets), primary checkpoint: %s.}\\label{tab:perclass%s}\n")
    write("perclass", head % ("LOACO", "") + "".join(body[:4]) + "\\end{table*}\n"
          + head % ("natural novelty", "nn") + "".join(body[4:]) + "\\end{table*}\n")


# ---------------------------------------------------------------- appendix: checkpoint
def t_checkpoint():
    rows = []
    for e in EV:
        ck = CS[e]["checkpoint"]
        rows.append(f"{EVN[e]} & " + " & ".join(f"{ck[f]['best']:.3f}/{ck[f]['final']:.3f}" for f in ("confidence", "representation", "CLAD")) + " \\\\")
    write("checkpoint", "\\begin{table}[t]\n\\centering\\scriptsize\\setlength{\\tabcolsep}{3pt}\n"
          "\\caption{Checkpoint sensitivity: family mean AUC at the best-validation / final-epoch state of the same "
          "training run.}\\label{tab:checkpoint}\n\\begin{tabular}{lccc}\n\\toprule\n"
          "Evaluation & Conf. & Repr. & CLAD \\\\\n\\midrule\n" + "\n".join(rows)
          + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n")


# ---------------------------------------------------------------- appendix: negative results
def t_negative():
    g = json.loads((ROOT / "results/p1/gate.json").read_text())
    b = json.loads((ROOT / "results/p1b/summary.json").read_text())
    c = json.loads((ROOT / "results/p1c/summary.json").read_text())
    d = json.loads((ROOT / "results/p1d/summary.json").read_text())
    G = d["gate"]["stats"]
    po = g["primary_oriented"]
    rho = ", ".join(f"{v['rho_gamma_dprime']:.3f}" for v in b["g1"]["datasets"].values())
    dp = c["gate"]["detectors_passing"]
    rows = [
        f"P1 & A spectral filter model predicts per-class zero-day detectability & $\\rho\\geq0.6$ and better than "
        f"Wasserstein & $\\rho={po['rho_S2']:.3f}$; diff.\\ CI [{po['diff_ci95'][0]:.3f}, {po['diff_ci95'][1]:.3f}] & {g['outcome']} \\\\",
        f"G1 & An adaptive equilibrium absorbs persistent attacks under supervised training & $\\rho(\\gamma,d')\\leq-0.8$ "
        f"on $\\geq$2 of 3 datasets & $\\rho$ = {rho} & {b['g1']['outcome']} \\\\",
        f"G2 & Benign drift causes inversion; re-anchoring fixes it & $\\geq$5 of 9 detectors per criterion & "
        f"{dp['a']}/9, {dp['b']}/9, {dp['c']}/9 & {c['gate']['outcome']} \\\\",
        f"G3 & Benign-only beat supervised scores only under natural novelty & $B-S\\geq0.15$ (NN), $\\leq0.05$ (LOACO) & "
        f"NN D5 {G['D5_nn']['B_minus_S']:+.3f}; LOACO D3 {G['D3_loaco']['B_minus_S']:+.3f} & {d['gate']['outcome']} \\\\"]
    write("negative", "\\begin{table*}[!b]\n\\centering\\scriptsize\n"
          "\\caption{Pre-registered confirmatory gates, evaluated as frozen; verdicts as recorded.}\\label{tab:negative}\n"
          "\\begin{tabular}{lp{5.6cm}p{3.6cm}p{3.6cm}l}\n\\toprule\nGate & Hypothesis & Frozen criterion & Observed & Verdict \\\\\n"
          "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n\\end{table*}\n")


def numbers():
    """Numbers quoted in the prose, recomputed here so the text can be checked against them."""
    st3n, st3l = CS["nn_D3"], CS["loaco_D3"]
    off = np.array([T[d][s][t]["mean"] for d in T for s in T[d] for t in T[d][s] if s != t])
    out = {
        "nnD3_ben_minus_repr": ci(st3n["contrasts"]["benign-only − representation"], True),
        "loacoD3_ben_minus_repr": ci(st3l["contrasts"]["benign-only − representation"], True),
        "clad_minus_ben_loacoD3": ci(st3l["clad_vs"]["benign-only"], True),
        "clad_minus_ben_nnD3": ci(st3n["clad_vs"]["benign-only"], True),
        "clad_minus_ben_loacoD2": ci(CS["loaco_D2"]["clad_vs"]["benign-only"], True),
        "clad_loacoD3_ddos": f3(st3l["cells"]["Wilkie_CLAD"]["ddos"]["mean"]),
        "nnD1_repr": ci(CS["nn_D1"]["families"]["representation"]),
        "nnD3_repr": ci(st3n["families"]["representation"]),
        "nnD3_knn_std": {c: round(v["std"], 3) for c, v in st3n["cells"]["kNN"].items()},
        "transfer_frac_03_06": float(np.mean((off >= 0.3) & (off <= 0.6))), "transfer_below_03": float(np.mean(off < 0.3)),
        "transfer_above_06": float(np.mean(off > 0.6)), "transfer_median": float(np.median(off)), "transfer_n": int(len(off)),
        "loacoD2_msp_all_below": all(st["frac_below_0.5"] == 1.0 for st in CS["loaco_D2"]["cells"]["MSP"].values()),
        "loacoD2_pattack_range": [round(min(v["mean"] for v in CS["loaco_D2"]["cells"]["P_attack"].values()), 3),
                                  round(max(v["mean"] for v in CS["loaco_D2"]["cells"]["P_attack"].values()), 3)],
        "contribution_checks": S.get("contribution_checks"),
    }
    (OUT / "numbers.json").write_text(json.dumps(out, indent=1))


if __name__ == "__main__":
    for f in (t_datasets, t_feasibility, t_families, t_seedstd, t_confidence, t_temporal, t_transfer, t_perclass,
              t_checkpoint, t_negative, numbers):
        f()
    print("tables:", sorted(p.name for p in OUT.glob("*")))
