#!/usr/bin/env python
"""Automatic P1 gate (rule frozen by the authors on 2026-10-05, no human judgement):

  rho_S2 = Spearman(D_pred, LOACO stress AUC) on the pooled set (D1 families + D2 + D3, grouped_random)
  rho_W  = the same for the Wasserstein predictor
  GO  iff rho_S2 >= 0.6 AND the lower 95% bound of (rho_S2 - rho_W) > 0,
      with a paired bootstrap over pooled points (2000 resamples, seed 0).

rho_W is taken ORIENTED (multiplied by the pre-registered expected sign, -1; RESEARCH_QUESTIONS.md
"Predictor sign"), which is how the frozen RQ file defines predictor comparisons. The raw-sign
variant is computed too; if the two variants give different outcomes the gate returns STOP and the
discrepancy is written to DECISIONS_PENDING.md (not resolved by choice).

Writes GATE_DECISION.md and results/p1/gate.json either way.
"""
import json, sys
from pathlib import Path
import numpy as np
from scipy.stats import spearmanr

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts")); sys.path.insert(0, str(ROOT / "src"))
import report_p1 as R  # noqa: E402
from nids.predictors import EXPECTED_SIGN  # noqa: E402
from nids.provenance import provenance, write_json  # noqa: E402

N_BOOT, SEED, RHO_MIN = 2000, 0, 0.6


def rho(x, y):
    return spearmanr(x, y)[0] if len(np.unique(x)) > 1 and len(np.unique(y)) > 1 else np.nan


def evaluate(points, w_sign):
    d = np.array([p["D_pred"] for p in points]); w = w_sign * np.array([p["wasserstein"] for p in points])
    a = np.array([p["auc_stress"]["mean"] for p in points])
    r_s2, r_w = rho(d, a), rho(w, a)
    rng = np.random.default_rng(SEED)
    diffs, valid = [], 0
    for _ in range(N_BOOT):
        i = rng.integers(0, len(a), len(a))
        x, y = rho(d[i], a[i]), rho(w[i], a[i])
        if np.isfinite(x) and np.isfinite(y):
            diffs.append(x - y); valid += 1
    lo, hi = np.percentile(diffs, [2.5, 97.5])
    go = bool(r_s2 >= RHO_MIN and lo > 0)
    return {"rho_S2": float(r_s2), "rho_W": float(r_w), "w_sign": w_sign, "diff": float(r_s2 - r_w),
            "diff_ci95": [float(lo), float(hi)], "n_points": int(len(a)), "n_boot": N_BOOT,
            "n_boot_valid": valid, "criterion_rho": bool(r_s2 >= RHO_MIN), "criterion_diff": bool(lo > 0),
            "outcome": "GO" if go else "STOP"}


def main():
    runs, _ = R.load(ROOT / "results/p1")
    points = [p for p in R.aggregate(runs) if p["rho_set"] in ("families", "pooled")]
    primary = evaluate(points, EXPECTED_SIGN["wasserstein"])   # oriented (pre-registered)
    raw = evaluate(points, +1)
    agree = primary["outcome"] == raw["outcome"]
    outcome = primary["outcome"] if agree else "STOP"
    res = {"rule": __doc__.strip(), "primary_oriented": primary, "raw_sign_variant": raw,
           "variants_agree": agree, "outcome": outcome,
           "points": [{"eval_id": p["eval_id"], "class": p["class"], "D_pred": p["D_pred"],
                       "wasserstein": p["wasserstein"], "auc_stress": p["auc_stress"]["mean"]} for p in points],
           "provenance": provenance()}
    write_json(ROOT / "results/p1/gate.json", res)
    f = lambda v: f"{v:.3f}"
    L = ["# GATE_DECISION", "", f"**Outcome: {outcome}**", "",
         "Rule (frozen 2026-10-05): GO iff ρ_S2 ≥ 0.6 and the lower 95% bound of (ρ_S2 − ρ_W) > 0, "
         "paired bootstrap over pooled points (D1 families + D2 + D3, grouped_random), 2000 resamples, seed 0.", "",
         "| Variant | ρ_S2 | ρ_W | ρ_S2 − ρ_W | 95% CI of difference | ρ_S2 ≥ 0.6 | CI lower > 0 | outcome |",
         "|---|---|---|---|---|---|---|---|"]
    for name, v in (("oriented ρ_W (primary, pre-registered sign −)", primary), ("raw-sign ρ_W", raw)):
        L.append(f"| {name} | {f(v['rho_S2'])} | {f(v['rho_W'])} | {f(v['diff'])} | [{f(v['diff_ci95'][0])}, "
                 f"{f(v['diff_ci95'][1])}] | {'yes' if v['criterion_rho'] else 'no'} | "
                 f"{'yes' if v['criterion_diff'] else 'no'} | {v['outcome']} |")
    L += ["", f"Pooled points: {primary['n_points']}; valid bootstrap resamples: {primary['n_boot_valid']}/{N_BOOT}.",
          f"Variants agree: {'yes' if agree else 'NO -> STOP, recorded in DECISIONS_PENDING.md'}.", "",
          f"Code commit: `{res['provenance']['code_commit']}`; RQ SHA-256 `{res['provenance']['rq_sha256']}`.",
          "Generated by `scripts/gate_p1.py` from `results/p1` JSON.", ""]
    (ROOT / "GATE_DECISION.md").write_text("\n".join(L))
    if not agree:
        with open(ROOT / "DECISIONS_PENDING.md", "a") as fh:
            fh.write("\n## P1 gate: oriented and raw-sign Wasserstein comparisons disagree\n"
                     f"Oriented: {primary['outcome']} (diff CI {primary['diff_ci95']}); raw: {raw['outcome']} "
                     f"(diff CI {raw['diff_ci95']}). The gate rule does not say which sign; the frozen RQ file "
                     "uses oriented rho. Gate set to STOP pending an author decision.\n")
    print(outcome)
    return outcome


if __name__ == "__main__":
    main()
