#!/usr/bin/env python
"""P0 report from data/MANIFEST.json, audit/*.json and the pipeline JSON (no hand-typed numbers).

  python scripts/report_p0.py            # writes P0_REPORT.md and results/p0_summary.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from nids import schema  # noqa: E402
from nids.provenance import ROOT, provenance, write_json  # noqa: E402


def _j(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def _fmt_ms(ms: float) -> str:
    import datetime as dt
    return dt.datetime.fromtimestamp(ms / 1000, dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S.%f")[:-3] + "Z"


def main():
    cfg = yaml.safe_load(open(ROOT / "configs/data.yaml"))
    man = _j(ROOT / "data/MANIFEST.json")["datasets"]
    pub = _j(ROOT / "configs/uq_published_class_counts_v3.json")
    proc = ROOT / cfg["processed_dir"]
    common = _j(proc / "common_features.json")
    L, disc, summary = [], [], {"datasets": {}}

    L += ["# P0 report: real NF-v3 data", "",
          "Generated by `scripts/report_p0.py` from `data/MANIFEST.json`, `audit/*.json` and "
          "`data/processed/**/*.json`. P1 has **not** been run.", ""]

    # ---------------------------------------------------------------- downloads
    L += ["## 1. Downloads and manifest", "",
          "| ID | Dataset | File | Size (B) | Rows | Cols | S3 ETag verified | BagIt SHA-1 verified | Downloaded (UTC) |",
          "|---|---|---|---|---|---|---|---|---|"]
    for ds, m in man.items():
        L.append(f"| {ds} | {m['name']} | `{m['file']}` | {m['size_bytes']:,} | {m['row_count']:,} | {m['n_columns']} | "
                 f"{m['download']['s3_etag_verified']} | {m['bagit_sha1_verified']} | {m['download_date_utc']} |")
    L += ["", "| ID | Official URL | UQ name | eSpace PID | Licence |", "|---|---|---|---|---|"]
    for ds, m in man.items():
        d = m["download"]
        L.append(f"| {ds} | {m['url']} | {d['uq_rdm_name']} | {d['uq_espace_pid']} | {d['licence']} |")
    L += ["", "SHA-256 of the downloaded zip (raw file, never modified) and SHA-1 of the CSV inside it:", "",
          "| ID | SHA-256 (zip) | CSV member | SHA-1 (CSV, = BagIt manifest) |", "|---|---|---|---|"]
    for ds, m in man.items():
        L.append(f"| {ds} | `{m['sha256']}` | `{m['data_member']}` | `{m['data_sha1']}` |")
    L.append("")

    # ---------------------------------------------------------------- audits
    L += ["## 2. Audits (raw data, before any processing)", ""]
    for ds in man:
        a = _j(ROOT / cfg["audit_dir"] / f"{ds}.json")
        info = _j(proc / ds / "index_meta.json")
        if a is None:
            L += [f"### {ds}: no audit", ""]
            disc.append(f"{ds}: not audited")
            continue
        s = summary["datasets"].setdefault(ds, {})
        s["audit"] = {k: a[k] for k in ("rows", "n_columns", "nan_total", "inf_total")}
        L += [f"### {ds} — {man[ds]['name']}", "",
              f"- rows {a['rows']:,}; columns {a['n_columns']}; schema check: missing {a['schema_check']['missing'] or 'none'}, "
              f"unexpected {a['schema_check']['unexpected'] or 'none'}",
              f"- timestamp range: {_fmt_ms(a['timestamp_range_ms'][0])} → {_fmt_ms(a['timestamp_range_ms'][1])} "
              f"({a['timestamp_span_hours']:.2f} h); NaN timestamps {a['timestamp_nan']}; "
              f"file already time-sorted: {a['timestamps_sorted_in_file']}; END < START: {a['end_before_start']}",
              f"- NaN total {a['nan_total']:,}; inf total {a['inf_total']:,}"
              + (f"; NaN by column {a['nan_counts']}" if a["nan_counts"] else "")
              + (f"; inf by column {a['inf_counts']}" if a["inf_counts"] else ""),
              f"- Label counts {a['label_counts']}; Label/Attack consistency violations: {a['label_consistency_violations']}",
              ""]
        dt = {}
        for c, t in a["dtypes"].items():
            dt.setdefault(t, []).append(c)
        L += ["dtypes as loaded (pipeline read types; raw CSV is text): " +
              "; ".join(f"**{t}** ({len(cs)}): " + (", ".join(cs) if len(cs) <= 6 else f"{len(cs)} numeric feature columns")
                        for t, cs in dt.items()), ""]
        L += ["| Class (Attack) | Count (file) | Count (UQ page) | Match |", "|---|---|---|---|"]
        ref = (pub or {}).get("counts", {}).get(ds, {})
        ref_ci = {k.lower(): v for k, v in ref.items()}
        for c, n in sorted(a["attack_class_counts"].items(), key=lambda kv: -kv[1]):
            r = ref.get(c, ref_ci.get(c.lower()))
            ok = "yes" if r == n else ("case differs" if r == n and c not in ref else "**no**")
            if r is not None and c not in ref:
                ok = "count yes, name case differs" if r == n else "**no** (and case differs)"
            L.append(f"| {c} | {n:,} | {r if r is not None else '—'} | {ok} |")
            if r is None or r != n or c not in ref:
                disc.append(f"{ds}: class '{c}' file count {n:,} vs UQ page {r if r is not None else 'absent'}"
                            + (" (name case differs from UQ page)" if r is not None and c not in ref else ""))
        for c in ref:
            if c not in a["attack_class_counts"] and c.lower() not in {k.lower() for k in a["attack_class_counts"]}:
                L.append(f"| {c} | 0 | {ref[c]:,} | **no** |")
                disc.append(f"{ds}: UQ page lists class '{c}' ({ref[c]:,}) not present in file")
        if ref and sum(ref.values()) != a["rows"]:
            disc.append(f"{ds}: UQ page class counts sum to {sum(ref.values()):,}, file has {a['rows']:,} rows "
                        f"(difference {sum(ref.values()) - a['rows']:+,})")
        L.append("")

    # ---------------------------------------------------------------- windows
    L += ["## 3. Grouping, windowing and dedupe", "",
          "| ID | flows | 1-h groups | groups < 32 flows | windows | duplicates removed | dup. label conflicts | "
          "windows kept | benign windows | flows in no window | majority ties | LOACO allowed | peak RAM index (GB) |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for ds in man:
        i = _j(proc / ds / "index_meta.json")
        if not i:
            continue
        w, d = i["windowing"], i["dedupe"]
        L.append(f"| {ds} | {i['flows']:,} | {w['groups']} | {w['groups_too_short']} | {w['windows']:,} | "
                 f"{d['duplicates_removed']:,} ({d['duplicates_removed'] / max(w['windows'], 1):.1%}) | "
                 f"{d['duplicate_label_conflicts']:,} | {d['windows_after']:,} | {i['benign_windows_after_dedupe']:,} | "
                 f"{w['flows_not_in_any_window']:,} | {w['majority_ties']:,} | {i['loaco_allowed']} | "
                 f"{i.get('peak_rss_gb_process', float('nan')):.2f} |")
        summary["datasets"].setdefault(ds, {})["windows"] = {"groups": w["groups"], "windows": w["windows"],
                                                             "kept": d["windows_after"],
                                                             "duplicates_removed": d["duplicates_removed"]}
    L.append("")

    # ---------------------------------------------------------------- splits
    L += ["## 4. Splits, balanced sets, class coverage", ""]
    for ds in man:
        i = _j(proc / ds / "index_meta.json")
        if not i:
            continue
        for scheme, s in i["schemes"].items():
            sw = s["split"]["windows"]
            gr = {k: len(v) for k, v in s["split"]["groups"].items()}
            L += [f"### {ds} / {scheme}", "",
                  f"- groups: {gr}; windows: {sw}",
                  f"- classes in test but absent from train: {s['composition']['test_classes_absent_from_train'] or 'none'}; "
                  f"in val but absent from train: {s['composition']['val_classes_absent_from_train'] or 'none'}", "",
                  "| Set | benign | attack | total | available benign | available attack | ratio target |",
                  "|---|---|---|---|---|---|---|"]
            for k in ("train", "val", "test"):
                v = s["sets"][k]
                L.append(f"| {k} | {v['benign']:,} | {v['attack']:,} | {v['benign'] + v['attack']:,} | "
                         f"{v['available_benign']:,} | {v['available_attack']:,} | {v['target_ratio']}:1 |")
                if v["benign"] + v["attack"] < v["cap"]:
                    disc.append(f"{ds}/{scheme}: {k} set below cap ({v['benign'] + v['attack']:,} < {v['cap']:,}); "
                                f"limited by available {'benign' if v['available_benign'] < v['target_ratio'] * v['available_attack'] else 'attack'} windows")
            tn = s["sets"]["test_natural"]
            L += [f"| test_natural | — | — | {tn['n']:,} | — | — | attack fraction {tn['attack_fraction']:.4f} |", ""]
            cls = list(s["composition"]["windows_by_majority_class"]["train"].keys())
            L += ["Windows by majority class (all windows of each split, before balancing):", "",
                  "| Class | train | val | test |", "|---|---|---|---|"]
            for c in cls:
                comp = s["composition"]["windows_by_majority_class"]
                L.append(f"| {c} | {comp['train'][c]:,} | {comp['val'][c]:,} | {comp['test'][c]:,} |")
            L += ["", "| LOACO class | train windows | eligible | feasible | train b/a | val b/a | test b/held-out | note |",
                  "|---|---|---|---|---|---|---|---|"]
            if "skipped" in s["loaco"]:
                L.append(f"| — | — | — | — | — | — | — | {s['loaco']['skipped']} |")
            else:
                for c, v in s["loaco"].items():
                    if v.get("eligible"):
                        L.append(f"| {c} | {v['train_windows_majority']:,} | yes | {v['feasible']} | "
                                 f"{v['train']['benign']}/{v['train']['attack']} | {v['val']['benign']}/{v['val']['attack']} | "
                                 f"{v['test']['benign']}/{v['test']['attack']} | {v.get('reason', '')} |")
                    else:
                        L.append(f"| {c} | {v['train_windows_majority']:,} | no | — | — | — | — | {v.get('reason', '')} |")
            n_ok = sum(x["ok"] for x in s["verification"])
            L += ["", f"Index-stage validators: **{n_ok}/{len(s['verification'])} passed**.", ""]
            summary["datasets"][ds].setdefault("schemes", {})[scheme] = {
                "split_windows": sw, "sets": s["sets"], "validators_passed": n_ok,
                "validators_total": len(s["verification"]),
                "loaco_feasible": sorted(c for c, v in s["loaco"].items() if isinstance(v, dict) and v.get("feasible"))}

    # ---------------------------------------------------------------- cleaner/archives
    L += ["## 5. Cleaner, common features, archives", ""]
    if common:
        L += [f"Common feature list ({len(common['features'])} features, intersection over "
              f"{', '.join(common['datasets'])} × both split schemes; partial: {common['partial']}):", "",
              ", ".join(f"`{c}`" for c in common["features"]), ""]
        dropped_all = sorted(set(schema.EXPECTED_FEATURES) - set(common["features"]))
        L += [f"Not in the common list ({len(dropped_all)}): " + ", ".join(f"`{c}`" for c in dropped_all), ""]
    L += ["| ID | scheme | cleaner fit rows | dropped by cleaner (not fixed rules) | rows materialised | windows referenced | "
          "NaN/inf imputed | log1p negatives clipped | archive validators | peak RAM finalize (GB) |",
          "|---|---|---|---|---|---|---|---|---|---|"]
    for ds in man:
        i, am = _j(proc / ds / "index_meta.json"), _j(proc / ds / "archive_meta.json")
        if not (i and am):
            continue
        for scheme, s in i["schemes"].items():
            a = am["schemes"][scheme]
            dr = {c: r for c, r in s["cleaner_dropped"].items() if c not in schema.drop_map(cfg["keep_ttl"])}
            n_ok = sum(x["ok"] for x in a["verification"])
            L.append(f"| {ds} | {scheme} | {s['cleaner_fit_rows']:,} | "
                     + ("; ".join(f"`{c}`: {r}" for c, r in dr.items()) or "none")
                     + f" | {a['rows_materialised']:,} | {a['windows_referenced']:,} | {a['transform']['nonfinite_imputed']:,} | "
                       f"{a['transform']['log1p_negative_clipped']:,} | {n_ok}/{len(a['verification'])} | "
                       f"{am.get('peak_rss_gb_process', float('nan')):.2f} |")
    L.append("")
    tdir = proc / "transfer"
    if tdir.exists():
        L += ["Transfer packages (target rebuilt with the source cleaner; nothing fitted on target):", "",
              "| Source → target | scheme | rows | windows | validators | source cleaner SHA-256 |", "|---|---|---|---|---|---|"]
        for p in sorted(tdir.glob("*/meta.json")):
            t = _j(p)
            for scheme, a in t["schemes"].items():
                n_ok = sum(x["ok"] for x in a["verification"])
                L.append(f"| {t['source']} → {t['target']} | {scheme} | {a['rows_materialised']:,} | "
                         f"{a['windows_referenced']:,} | {n_ok}/{len(a['verification'])} | `{a['source_cleaner_sha256'][:16]}…` |")
        L.append("")

    # ---------------------------------------------------------------- validators
    L += ["## 6. Every validator result", ""]
    allv = []
    for ds in man:
        i, am = _j(proc / ds / "index_meta.json"), _j(proc / ds / "archive_meta.json")
        for scheme, s in (i or {}).get("schemes", {}).items():
            allv += [(ds, scheme, "index", v) for v in s["verification"]]
            if am:
                allv += [(ds, scheme, "archive", v) for v in am["schemes"][scheme]["verification"]]
    for p in sorted(tdir.glob("*/meta.json")) if tdir.exists() else []:
        t = _j(p)
        for scheme, a in t["schemes"].items():
            allv += [(f"{t['source']}→{t['target']}", scheme, "transfer", v) for v in a["verification"]]
    n_ok = sum(v["ok"] for *_, v in allv)
    L += [f"**{n_ok}/{len(allv)} passed.** (The pipeline fails closed: a failing check aborts before writing.)", "",
          "<details><summary>All checks</summary>", "", "| Where | scheme | stage | check | ok |", "|---|---|---|---|---|"]
    L += [f"| {w} | {sc} | {st} | {v['check']} | {v['ok']} |" for w, sc, st, v in allv]
    L += ["", "</details>", ""]
    summary["validators"] = {"passed": n_ok, "total": len(allv)}

    # ---------------------------------------------------------------- discrepancies
    L += ["## 7. Discrepancies between the real data and the specification / UQ page", ""]
    L += [f"- {x}" for x in disc] or ["- none found"]
    extra = _j(ROOT / "results" / "p0_notes.json") or {}
    L += [f"- {x}" for x in extra.get("discrepancies", [])]
    L.append("")
    summary["discrepancies"] = disc + extra.get("discrepancies", [])
    summary["provenance"] = provenance(config=cfg, data_sha256={ds: m["sha256"] for ds, m in man.items()})
    write_json(ROOT / "results" / "p0_summary.json", summary)
    (ROOT / "P0_REPORT.md").write_text("\n".join(L) + "\n")
    print(f"wrote P0_REPORT.md ({n_ok}/{len(allv)} validators passed, {len(summary['discrepancies'])} discrepancies)")


if __name__ == "__main__":
    main()
