#!/usr/bin/env python
"""P1d stop report (AMENDMENT_04): D5 P0 + feasibility, from JSON only.

Used when a frozen P1d evaluation is infeasible before any model run. Writes P1D_REPORT.md
and GATE_G3_DECISION.md (gate not evaluated) and results/p1d/feasibility_summary.json.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from nids.provenance import ROOT, provenance, rq_sha256, write_json  # noqa: E402


def main():
    man = json.loads((ROOT / "data/MANIFEST.json").read_text())["datasets"]["D5"]
    aud = json.loads((ROOT / "audit/D5.json").read_text())
    idx = json.loads((ROOT / "data/processed/D5/index_meta.json").read_text())
    arc = json.loads((ROOT / "data/processed/D5/archive_meta.json").read_text())
    feas = json.loads((ROOT / "results/p1d/d5_feasibility.json").read_text())
    pkg = json.loads((ROOT / "data/processed/D5/temporal_gap/p1d/p1c_meta.json").read_text())
    gr = idx["schemes"]["grouped_random"]
    loaco_feasible = [c for c, r in gr["loaco"].items() if r.get("eligible") and r.get("feasible")]
    nn_ok = feas["feasible"]
    S = {"d5_natural_novelty_feasible": nn_ok, "d5_loaco_feasible_folds": loaco_feasible,
         "outcome": "STOP (not evaluated): D5 LOACO infeasible" if not loaco_feasible else "feasible",
         "rq_sha256": rq_sha256(), "provenance": provenance()}
    write_json(ROOT / "results/p1d/feasibility_summary.json", S)
    comp = gr["composition"]["windows_by_majority_class"]
    tg = idx["schemes"]["temporal_gap"]
    L = ["# P1d report — stopped before any model run", "",
         "Generated by `scripts/report_p1d_feasibility.py` from JSON (manifest, audit, pipeline metadata, feasibility). "
         "Scope: AMENDMENT_04. **No P1d model was trained or scored.**", "",
         "## Why P1d stopped", "",
         f"- **D5 LOACO (grouped_random) has {len(loaco_feasible)} feasible folds.** A4.5 requires D5 LOACO and gate G3 "
         "criterion (b) is computed on it, so G3 cannot be evaluated as frozen. Every attack class with ≥ 200 training "
         "windows is absent from the grouped_random test split (table below): D5 has only "
         f"{idx['windowing']['groups']} one-hour groups (5 working days) and each attack class occupies a few hours, so the "
         "shuffled 60/20/20 group split places each class wholly in one split.",
         f"- D5 natural_novelty is feasible: test-only classes {', '.join(feas['evaluable_classes'])} "
         f"({feas['test_windows']} test windows); train-tail validation holds {feas['train_tail']['attack']} attack windows "
         f"({feas['train_tail']['attack_classes']}) and {feas['train_tail']['benign']} benign windows, giving a "
         f"{pkg['sets']['val']['benign']} + {pkg['sets']['val']['attack']} validation set.",
         "- The remaining A4.5 evaluations (D5 natural_novelty, D3 LOACO with 10 detectors, D3 natural_novelty Wilkie) were "
         "not run: without D5 LOACO the frozen gate cannot decide, and running them first would expose results before an "
         "author decision on D5 LOACO.", "",
         "## D5 (Lycos2017) P0", "",
         f"- Source: {man['landing']} → `{man['url']}`; archive SHA-256 `{man['archive_sha256']}` "
         f"({man['archive_size_bytes']:,} B); authors' `labelling.py` SHA-256 `{man['labelling_py_sha256']}` run unmodified "
         f"(worker-count prompt answered {man['labelling_py_stdin_workers']}); derived file `{man['file']}` SHA-256 "
         f"`{man['sha256']}`.",
         f"- Rows {aud['rows']:,}; columns {aud['n_columns']} (after the adapter); timestamp span {aud['timestamp_span_hours']:.1f} h; "
         f"NaN {aud['nan_total']}, inf {aud['inf_total']}; Label/Attack violations {aud['label_consistency_violations']}.",
         f"- Label counts (equal to the authors' labelling log): {man['label_counts_labelling_py']}.",
         f"- Windows {idx['windowing']['windows']:,} (T = 32, stride 16) in {idx['windowing']['groups']} one-hour groups; "
         f"duplicates removed {idx['dedupe']['duplicates_removed']}; benign windows {idx['benign_windows_after_dedupe']:,}.",
         f"- Own feature space: {len(gr['cleaner_kept'])} features kept (zero-variance drops: "
         f"{', '.join(c for c, r in gr['cleaner_dropped'].items() if 'variance' in r)}).",
         f"- Validators: index temporal_gap {sum(v['ok'] for v in tg['verification'])}/{len(tg['verification'])}, "
         f"grouped_random {sum(v['ok'] for v in gr['verification'])}/{len(gr['verification'])}; archives "
         + ", ".join(f"{s} {sum(v['ok'] for v in a['verification'])}/{len(a['verification'])}" for s, a in arc["schemes"].items())
         + f"; natural_novelty package {len(pkg['verification'])}/{len(pkg['verification'])}.", "",
         "## D5 windows by majority class (grouped_random: train / val / test)", "",
         "| Class | train | val | test | LOACO |", "|---|---|---|---|---|"]
    for c in comp["train"]:
        if c == "Benign":
            L.append(f"| {c} | {comp['train'][c]:,} | {comp['val'][c]:,} | {comp['test'][c]:,} | — |")
            continue
        r = gr["loaco"][c]
        L.append(f"| {c} | {comp['train'][c]:,} | {comp['val'][c]:,} | {comp['test'][c]:,} | "
                 f"{'feasible' if r.get('feasible') else r.get('reason', '')} |")
    t = tg["composition"]["windows_by_majority_class"]
    L += ["", "## D5 windows by majority class (temporal_gap: train / val / test)", "",
          "| Class | train | val | test |", "|---|---|---|---|"]
    for c in t["train"]:
        L.append(f"| {c} | {t['train'][c]:,} | {t['val'][c]:,} | {t['test'][c]:,} |")
    L += ["", "## Provenance", "",
          f"- RESEARCH_QUESTIONS.md SHA-256 in force: `{S['rq_sha256']}` (AMENDMENT_04).",
          f"- Report generated at `{S['provenance']['code_commit']}`.", ""]
    (ROOT / "P1D_REPORT.md").write_text("\n".join(L))
    G = ["# GATE_G3_DECISION", "", "**Outcome: STOP — gate not evaluated (D5 LOACO infeasible).**", "",
         "Rule (AMENDMENT_04 A4.6, frozen): GO only if (a) D5 natural_novelty B − S ≥ 0.15 with CI > 0, (b) D5 LOACO "
         "B − S ≤ 0.05, (c) the same pattern on D3.", "",
         f"| Criterion | status |", "|---|---|",
         f"| (a) D5 natural_novelty | not run (evaluation feasible: {', '.join(feas['evaluable_classes'])}) |",
         f"| (b) D5 LOACO | **cannot be computed: {len(loaco_feasible)} feasible folds** |",
         "| (c) D3 natural_novelty + LOACO | not run |", "",
         "No P1d model was trained or scored. Details: `P1D_REPORT.md`. Generated by `scripts/report_p1d_feasibility.py`.", ""]
    (ROOT / "GATE_G3_DECISION.md").write_text("\n".join(G))
    print(S["outcome"])


if __name__ == "__main__":
    main()
